
package com.clkio.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.clkio.schemas.adjusting.DeleteAdjustingRequest;
import com.clkio.schemas.adjusting.InsertAdjustingRequest;
import com.clkio.schemas.adjusting.ListAdjustingRequest;
import com.clkio.schemas.adjusting.ListAdjustingResponse;
import com.clkio.schemas.adjusting.UpdateAdjustingRequest;
import com.clkio.schemas.common.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdjustingPort", targetNamespace = "http://ws.clkio.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.clkio.schemas.ObjectFactory.class,
    com.clkio.schemas.adjusting.ObjectFactory.class,
    com.clkio.schemas.clockinclockout.ObjectFactory.class,
    com.clkio.schemas.common.ObjectFactory.class,
    com.clkio.schemas.day.ObjectFactory.class,
    com.clkio.schemas.email.ObjectFactory.class,
    com.clkio.schemas.login.ObjectFactory.class,
    com.clkio.schemas.manualentering.ObjectFactory.class,
    com.clkio.schemas.profile.ObjectFactory.class,
    com.clkio.schemas.reason.ObjectFactory.class,
    com.clkio.schemas.resetpassword.ObjectFactory.class,
    com.clkio.schemas.timecard.ObjectFactory.class,
    com.clkio.schemas.user.ObjectFactory.class
})
public interface AdjustingPort {


    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.adjusting.ListAdjustingResponse
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "listAdjustingResponse", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public ListAdjustingResponse list(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "listAdjustingRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        ListAdjustingRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response insert(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "insertAdjustingRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        InsertAdjustingRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response update(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "updateAdjustingRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        UpdateAdjustingRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response delete(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "deleteAdjustingRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        DeleteAdjustingRequest request)
        throws ResponseException
    ;

}
