
package com.clkio.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.clkio.schemas.common.Response;
import com.clkio.schemas.email.ConfirmEmailRequest;
import com.clkio.schemas.email.DeleteEmailRequest;
import com.clkio.schemas.email.InsertEmailRequest;
import com.clkio.schemas.email.ListEmailRequest;
import com.clkio.schemas.email.ListEmailResponse;
import com.clkio.schemas.email.SetEmailAsPrimaryRequest;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmailPort", targetNamespace = "http://ws.clkio.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.clkio.schemas.ObjectFactory.class,
    com.clkio.schemas.adjusting.ObjectFactory.class,
    com.clkio.schemas.clockinclockout.ObjectFactory.class,
    com.clkio.schemas.common.ObjectFactory.class,
    com.clkio.schemas.day.ObjectFactory.class,
    com.clkio.schemas.email.ObjectFactory.class,
    com.clkio.schemas.login.ObjectFactory.class,
    com.clkio.schemas.manualentering.ObjectFactory.class,
    com.clkio.schemas.profile.ObjectFactory.class,
    com.clkio.schemas.reason.ObjectFactory.class,
    com.clkio.schemas.resetpassword.ObjectFactory.class,
    com.clkio.schemas.timecard.ObjectFactory.class,
    com.clkio.schemas.user.ObjectFactory.class
})
public interface EmailPort {


    /**
     * 
     * @param request
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response confirm(
        @WebParam(name = "confirmEmailRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        ConfirmEmailRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response insert(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "insertEmailRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        InsertEmailRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.email.ListEmailResponse
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "listEmailResponse", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public ListEmailResponse list(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "listEmailRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        ListEmailRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response delete(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "deleteEmailRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        DeleteEmailRequest request)
        throws ResponseException
    ;

    /**
     * 
     * @param request
     * @param clkioLoginCode
     * @return
     *     returns com.clkio.schemas.common.Response
     * @throws ResponseException
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "http://schemas.clkio.com", partName = "result")
    public Response setEmailAsPrimary(
        @WebParam(name = "clkioLoginCode", targetNamespace = "http://schemas.clkio.com", header = true, partName = "clkioLoginCode")
        String clkioLoginCode,
        @WebParam(name = "setEmailAsPrimaryRequest", targetNamespace = "http://schemas.clkio.com", partName = "request")
        SetEmailAsPrimaryRequest request)
        throws ResponseException
    ;

}
