
package com.clkio.ws;

import javax.xml.ws.WebFault;

import com.clkio.schemas.common.Response;
import com.clkio.schemas.common.ResponseFault;
import com.clkio.web.constants.AppConstants;
import com.clkio.web.enums.ContentType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "responseFault", targetNamespace = "http://schemas.clkio.com")
public class ResponseException
    extends Exception
{

	private static final long serialVersionUID = AppConstants.SERIAL_VERSION_UID;
	
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResponseFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ResponseException(String message, ResponseFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ResponseException(String message, ResponseFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.clkio.schemas.common.ResponseFault
     */
    public ResponseFault getFaultInfo() {
        return faultInfo;
    }
    
    public int getStatusCode() {
    	return faultInfo != null && faultInfo.getStatusCode() != null ?
    			Integer.parseInt( faultInfo.getStatusCode() ) : 500;
    }
    
    public String getMessage( ContentType accept ) {
    	return new Response( this.getMessage() ).getMessage( accept );
	}

    
    
}
